php:
  build: .
  ports:
    - "8000:80"
    - "443:443"
  volumes:
    - ./www:/var/www/html
  links:
    - db

db:
  image: mysql:5.7
  volumes:
    - ./data_db:/var/lib/mysql
  ports:
    - "3306:3306"  
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=teste


